version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
    day: friday
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
